# Site settings
name : "~/hayderimran7"
author: "Imran Hayder"
title: "Welcome to my GH blog" 
email: "hayderimran7@gmail.com"	
description: > # this means to ignore newlines until "baseurl:"
  A website based on GH pages created Jekyll. Its intended purpose is to 
  serve my short blogs related to engineering, programming, CI systems etc.
   
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hayderimran7.github.io"
twitter_username: hayderimran7
github_username:  hayderimran7

# Build settings
markdown: redcarpet
